### ISSUE TITLE
what is the overhead of CAS up-scaling? 

### ISSUE THREAD

**Issue by tingxingdong** [GPUOpen-Effects/FidelityFX#3]
Suppose I have a 4K monitor but I play 1K (1080p) game since my Navi 5700 is not so powerful. 

1) I can leave the 4K  display to upscale my image from 1K to 4K.  (I understand the quality is not good) 
or 
2) I can use CAS (or called RIS on driver)  to upscale 1K to 4K (I want to get better quality).    

Compared to option 1, what is overhead of option 2? How many FPS drop on Navi 5700 from option 1 to option 2?
Can you give an estimation if not specific data? 
Thanks

**Comment by SurenaSKQ** [comment]
The performance drop is virtually non-existent.
