### ISSUE TITLE
Can build CAS_SAMPLE_DX12 exe but sharpen button no effect 

### ISSUE THREAD

**Issue by tingxingdong** [GPUOpen-Effects/FidelityFX#4]
I can build and run CAS sample and see the helmet on display only when "NO CAS".  The "CAS upsample" and "CAS sharpen only" buttons on the left panel have no effect. When enabling either of them, the helmet disappear.  Using keyboard mode "e" has no effect, too. 

![image](https://user-images.githubusercontent.com/15220823/68707400-4bc95200-0557-11ea-92fe-268a6ebbda0a.png)

**Comment by rys** [comment]
Can't repro using CAS v1.0.1 and modern drivers, but please feel free to file the bug again if it still doesn't work for you. Sorry it took such a long time to get to this bug report.
