### ISSUE TITLE
threadpool.h missing #include <functional>

### ISSUE THREAD

**Issue by reto-hal9k** [GPUOpen-Effects/FidelityFX#5]
I have to add this line manually in order to be able to build using VS2019 16.4.4
FFX_CAS\cas-samples\build\GenerateSolutions was used to generate the solution file.

**Comment by rys** [comment]
Fixed in [e53b3cf](https://github.com/GPUOpen-LibrariesAndSDKs/Cauldron/commit/e53b3cff20f19cc3bc5873ff170fc13a23d4aafb) and CAS was updated to build with Cauldron v1.1 in a subsequent release.
